CREATE TABLE IF NOT EXISTS USER_ACCT_INFO (
    USERID      VARCHAR(32) PRIMARY KEY,
    USERNAME    VARCHAR(16) NOT NULL,
    SALT        CHAR(64)    NOT NULL,
    HASH        CHAR(64)    NOT NULL
);